# _config.yml
title: Abisal Wiki
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Incluir páginas desde la carpeta _pages
include:
  - _pages

# Configuración para GitHub Pages (si lo subirás a GitHub)
url: "https://sagarinnus.github.io/"  # Cambia 
# Deja vacío si es tu sitio principal (user.github.io)
baseurl: "/Abisales_Wiki/"
